# Sorts `Cargo.toml` dependencies. All other `.toml` files are formatted with the default config.
#
# https://taplo.tamasfe.dev/configuration/file.html#configuration-file

[formatting]
align_entries = true
column_width  = 120
reorder_keys  = false

[[rule]]
include = ["**/Cargo.toml", "Cargo.toml"]
keys    = ["dependencies", "workspace.dependencies"]

[rule.formatting]
reorder_keys = true
